# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
rvm: 1.9.3
cache: cocoapods
podfile: Example/Podfile
before_install:
    - gem update --system
    - gem install cocoapods # Since Travis is not always on latest version
    - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/PlainPing.xcworkspace -scheme PlainPing-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
